export default {
  name: 'newsMarquee',
  key: 'news-marquee',
  text: '滚动新闻',
  icon: 'fa-newspaper-o',
  category: 'animate',
  projectTypes: [],
  condition: {},
  default: {
    title: '倒计时',
    domId: '',
    domName: '',
    style: [
      {
        type: 'radio',
        label: '是否连续',
        attr: 'goon',
        val: false,
        options: [
          {
            name: '连续',
            val: true,
          },
          {
            name: '不连续',
            val: false,
          },
        ],
      },
      {
        type: 'upload',
        label: '背景图片',
        attr: 'background-image',
        val: '',
        isNecessary: true,
      },
      {
        type: 'input-number',
        label: '容器高度',
        attr: 'height',
        val: 40,
        unit: 'px',
        min: 0,
        max: 100,
        step: 1,
        isNecessary: true,
      },
      {
        type: 'input-number',
        label: '右边距',
        attr: 'padding-right',
        val: 10,
        unit: 'px',
        min: 0,
        max: 50,
        step: 1,
        isNecessary: true,
      },
      {
        type: 'input-number',
        label: '左边距',
        attr: 'padding-left',
        val: 10,
        unit: 'px',
        min: 0,
        max: 50,
        step: 1,
        isNecessary: true,
      },
      {
        type: 'input-number',
        label: '字体大小',
        attr: 'font-size',
        val: 12,
        unit: 'px',
        min: 0,
        max: 60,
        step: 1,
        isNecessary: true,
      },
      {
        type: 'font',
        label: '字体',
        attr: ['font-weight', 'text-decoration', 'font-style', 'text-align'],
        val: ['400', 'none', 'inherit', 'left'],
        isNecessary: false,
      },
      {
        type: 'color-picker',
        label: '字体颜色',
        attr: 'color',
        val: '#333333',
        isNecessary: true,
      },
    ],
    action: {
      type: 'marquee-click',
      title: '滚动项配置',
    },
    settings: {
      config: [
        {
          text: '滚动新闻默认文本',
          click: null,
        },
      ],
    },
  },
}
