export default {
  name: 'horizontalList',
  key: 'horizontal-list',
  text: '横向列表',
  icon: 'fa-th-list',
  category: 'list',
  projectTypes: [],
  condition: {},
  default: {
    title: '横向列表',
    domId: '',
    domName: '',
    style: [
      {
        type: 'color-picker',
        label: '背景颜色',
        attr: 'background-color',
        val: '#ffffff',
        isNecessary: false,
      },
      {
        type: 'input-number',
        label: '左内边距',
        attr: 'padding-left',
        val: 15,
        unit: 'px',
        min: 0,
        max: 50,
        step: 1,
        isNecessary: true,
      },
      {
        type: 'input-number',
        label: '右内边距',
        attr: 'padding-right',
        val: 15,
        unit: 'px',
        min: 0,
        max: 50,
        step: 1,
        isNecessary: true,
      },
    ],
    others: {
      type: 'item-style',
      title: '列表项样式',
      config: [
        {
          type: 'input-number',
          label: '上内边距',
          attr: 'horizontal-list-item_padding-top',
          val: 10,
          unit: 'px',
          min: 0,
          max: 50,
          step: 1,
          isNecessary: true,
        },
        {
          type: 'input-number',
          label: '下内边距',
          attr: 'horizontal-list-item_padding-bottom',
          val: 10,
          unit: 'px',
          min: 0,
          max: 50,
          step: 1,
          isNecessary: true,
        },
        {
          type: 'input-number',
          label: '图片宽度',
          attr: 'horizontal-list-logo_width',
          val: 100,
          unit: 'px',
          step: 1,
          max: 300,
          min: 10,
          isNecessary: false,
        },
        {
          type: 'input-number',
          label: '图片高度',
          attr: 'horizontal-list-logo_height',
          val: 60,
          unit: 'px',
          step: 1,
          max: 300,
          min: 10,
          isNecessary: false,
        },
        {
          type: 'input-number',
          label: '标题大小',
          attr: 'horizontal-list-title_font-size',
          val: 16,
          unit: 'px',
          step: 1,
          max: 100,
          min: 10,
          isNecessary: false,
        },
        {
          type: 'color-picker',
          label: '标题颜色',
          attr: 'horizontal-list-title_color',
          val: '#333333',
          isNecessary: false,
        },
        {
          type: 'input-number',
          label: '标题粗细',
          attr: 'horizontal-list-title_font-weight',
          val: 500,
          unit: '',
          min: 300,
          max: 900,
          step: 100,
          isNecessary: true,
        },
        {
          type: 'input-number',
          label: '描述大小',
          attr: 'horizontal-list-desc_font-size',
          val: 13,
          unit: 'px',
          step: 1,
          max: 100,
          min: 10,
          isNecessary: false,
        },
        {
          type: 'color-picker',
          label: '描述颜色',
          attr: 'horizontal-list-desc_color',
          val: '#999999',
          isNecessary: false,
        },
      ],
    },
    action: {
      type: 'horizontal-item-click',
      title: '列表项配置',
    },
    settings: {
      config: [
        {
          val: '',
          title: '默认标题',
          desc: '默认文案描述，默认文案描述，默认文案描述默认文案描述',
          click: null,
        },
      ],
    },
  },
}
