export default {
  name: 'pageIntro',
  key: 'page-intro',
  text: '引言模块',
  icon: 'fa-quote-left',
  category: 'pageModule',
  projectTypes: [],
  condition: {},
  default: {
    title: '引言模块',
    domId: '',
    domName: '',
    base: [
      {
        type: 'textarea',
        label: '文本内容',
        val: '这是一个移动端页面设计和制作平台，无需任何开发经营也可以制作自己的移动端站点和页面，从灵感到实现，您只需要10分钟。',
        isNecessary: true,
      },
    ],
    style: [
      {
        type: 'color-picker',
        label: '字体颜色',
        attr: 'color',
        val: '#999999',
        isNecessary: true,
      },
      {
        type: 'input-number',
        label: '字体大小',
        attr: 'font-size',
        val: 12,
        unit: 'px',
        step: 1,
        max: 100,
        min: 10,
        isNecessary: false,
      },
      {
        type: 'input-number',
        label: '文本行距',
        attr: 'line-height',
        val: 1.5,
        step: 0.5,
        max: 12,
        min: 0.5,
        isNecessary: false,
      },
      {
        type: 'input-number',
        label: '上边距',
        attr: 'padding-top',
        val: 10,
        unit: 'px',
        min: 0,
        max: 50,
        step: 1,
        isNecessary: true,
      },
      {
        type: 'input-number',
        label: '右边距',
        attr: 'padding-right',
        val: 15,
        unit: 'px',
        min: 0,
        max: 50,
        step: 1,
        isNecessary: true,
      },
      {
        type: 'input-number',
        label: '下边距',
        attr: 'padding-bottom',
        val: 10,
        unit: 'px',
        min: 0,
        max: 50,
        step: 1,
        isNecessary: true,
      },
      {
        type: 'input-number',
        label: '左边距',
        attr: 'padding-left',
        val: 15,
        unit: 'px',
        min: 0,
        max: 50,
        step: 1,
        isNecessary: true,
      },
    ],
  },
}
